## 2.5 Исключения

> [[_оглавление_]](../README.md/#25-исключения)

[**Исключения (Exceptions)**](/conspect/definitions.md/#и) - это механизм, который позволяет программе обрабатывать
нетипичную ситуацию и при этом не прекращать работу.

### 2.5.1 Иерархия исключений

> [[_оглавление_]](../README.md/#25-исключения)

![14.png](/pictures/14.png)

Исключения имеют общего предка - класс _Throwable_. Его потомками являются подклассы _Exception_ и _Error_.  
_Исключения (Exceptions)_ являются результатом проблем в программе, которые в принципе решаемы и предсказуемы.  
_Ошибки (Errors)_ представляют собой более серьёзные проблемы, которые, согласно спецификации Java, не следует пытаться
обрабатывать в собственной программе, поскольку они связаны с проблемами уровня _JVM_.

Все исключения подразделяются на _проверяемые_ и _непроверяемые_.  
К непроверяемым исключениям относятся все ошибки (класс _Error_ и его потомки) и все исключения времени выполнения
(класс _RuntimeException_ и его потомки), к проверяемым - все остальные.

В коде можно создавать и выбрасывать свои исключения.

Синтаксис выброса исключений выглядит следующим образом:

```java
throw new RuntimeException();
```

> [**throw**](/conspect/definitions.md/#t) – это ключевое слово, которое применяется для выбрасывания исключений в коде.

При возникновении исключения в Java-коде модуль _Spring Web_ возвращает пользователю соответствующий _HTTP_-статус.

> [**Ссылка**](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) на список возможных _HTTP_-статусов.

Чтобы сообщить _Spring_, какой именно статус необходимо возвращать пользователю, используют аннотацию `@ResponseStatus`.

### 2.5.2 Обработка исключений

> [[_оглавление_]](../README.md/#25-исключения)

Когда проверяемое исключение не обрабатывается внутри того метода, где это исключение кидается, необходимо использовать
ключевое слово `throws` и указывать тип выбрасываемого проверяемого исключения.

Например:

```java
public static void check(File file) throws FileNotFoundException {
    if (!file.exists()) {
        throw new FileNotFoundException();
    }
    if (file.isDirectory()) {
        throw new IllegalArgumentException(file.getPath() + " is a directory");
    }
}
```

> [**throws**](/conspect/definitions.md/#t) – это ключевое слово, которое используется в объявлении метода для указания,
> что метод может выбрасывать проверяемые исключения.  
> При использовании ключевого слова `throws` проверка выбрасываемого исключения делегируется тому методу, который
> вызывает данный.

Обработка исключений в Java построена на конструкции _try-catch-finally_.

![15.png](/pictures/15.png)

> [**try**](/conspect/definitions.md/#t) – это ключевое слово, определяющее блок кода, в котором может произойти
> исключение.

> [**catch**](/conspect/definitions.md/#c) – это ключевое слово, определяющее блок кода, в котором происходит обработка
> исключения.

> [**finally**](/conspect/definitions.md/#f) – это ключевое слово, определяющее блок кода, который является
> необязательным, но при его наличии выполняется в любом случае независимо от результатов выполнения блока `try`.  
> Блок `finally` иерархически выше блока `try`. Это означает, что если оба блока будут содержать оператор `return`, то
> выполнится тот, который содержится в блоке `finally`.

Конструкция _try-catch-finally_ выглядит следующим образом:

```text
try([создание какого-либо ресурса])
{
    // код, в котором может возникнуть исключение
}
catch([тип исключения] [имя переменной])
{
    // действия по обработке исключения
}
finally
{
    // код, выполняемый в любом случае
}
```

Блоки `catch` могут объединяться в цепочки, а также отвечать за обработку нескольких типов исключений. В последнем
случае типы обрабатываемых исключений указываются через вертикальную черту (`|`).

Например:

```java
private static void tryCatchFinallyExample() {
    try {
        File file = new File("pictures/16.png");
        System.out.println(Files.size(file.toPath()));
    } catch (NoSuchElementException e) {
        System.out.println("File not found!");
    } catch (IOException | ClassCastException e) {
        System.out.println("Internal error!");
    } finally {
        System.out.println("The end");
    }
}
```

> [[_Примеры использования_]](/conspect/example_1.md/#пример-1)

Блоки `catch` анализируются по очереди. И если указать родительское исключение раньше, чем его наследника, то будет
вызван код из первого совпавшего блока, а не из более узкоспециализированного, но написанного после.

Блок `try` также применяется в многопоточных приложениях для того, чтобы гарантированно закрывать открываемые в процессе
выполнения потоки. Такая конструкция с использованием блока `try` называется _try-with-resources_.

### 2.5.3 Написание своих исключений

> [[_оглавление_]](../README.md/#25-исключения)

Исключение представляет собой обычный класс, не имеющий собственных методов, наследующийся от _Exception_ или от
_RuntimeException_ и вызывающий соответствующий конструктор родителя.

Например:

```java
import java.io.IOException;

@ResponseStatus(HttpStatus.BAD_REQUEST)
public class FileIsDirectoryException extends IOException {
    public FileIsDirectoryException() {
        super();
    }

    public FileIsDirectoryException(String message) {
        super(message);
    }

    public FileIsDirectoryException(String message, Throwable t) {
        super(message, t);
    }

    public FileIsDirectoryException(Throwable t) {
        super(t);
    }
}
```

После создания свои исключения могут использоваться точно также как и библиотечные исключения Java с использованием
ключевого слова `throw`.